/**
 * The benchmark report view — a rendering of the report JSON and nothing else.
 *
 * Published tables are generated by the scoring harness, never hand-assembled,
 * and this view keeps that property: every cell traces to a field the harness
 * wrote, and fields the harness does not write are named as missing.
 */

import { AREA_BINS_HA } from './data'
import type { LoadedBenchmark } from './data'
import { type Raw, fixed, html, percent } from './dom'
import type { BenchmarkReport, CalibrationBin, KillCriterionStatus } from './types'

export function renderReport(loaded: LoadedBenchmark): Raw {
  const { report } = loaded
  return html`
    <div class="report-inner">
      ${renderVerdict(loaded)}
      <div class="report-section-label">Kill criteria — stated before building</div>
      ${renderCriteria(report)}
      <div class="report-section-label">Event-level metrics</div>
      ${renderMetrics(report)}
      <div class="two-col">
        <div>
          <div class="report-section-label" style="margin-top:0">Confidence calibration</div>
          ${renderCalibration(report)}
        </div>
        <div>
          <div class="report-section-label" style="margin-top:0">Recall by event size</div>
          ${renderRecallByArea(report)}
        </div>
      </div>
      <div class="report-section-label">Run history</div>
      ${renderRuns(loaded)}
      <div class="note">
        Published tables are generated by the scoring harness, never hand-assembled. Synthetic
        passes are scaffolding, never claims. Full report:
        <a href="${loaded.resolved.report}">${loaded.resolved.report}</a> · alerts:
        <a href="${loaded.resolved.alerts}">${loaded.resolved.alerts}</a> · labels:
        <a href="${loaded.resolved.labels}">${loaded.resolved.labels}</a>
      </div>
    </div>
  `
}

function renderVerdict(loaded: LoadedBenchmark): Raw {
  const { report } = loaded
  const verdict = report.killCriteria
  const failed = verdict.criteria.filter((c) => c.status === 'FAIL').length
  const unknown = verdict.criteria.filter((c) => c.status === 'INSUFFICIENT_DATA').length
  const notes = [
    failed === 0 ? 'No kill condition met' : `${failed} kill condition met`,
    unknown ? `${unknown} criterion lacks data — unknown is not dead` : null,
  ].filter(Boolean)
  return html`
    <div class="verdict ${verdict.alive ? '' : 'is-dead'}">
      <div class="verdict-dot"></div>
      <div>
        <div class="verdict-title">
          VERDICT: ${verdict.alive ? 'THESIS ALIVE' : 'KILL CONDITION MET'}
        </div>
        <div class="verdict-note">
          ${notes.join(' · ')}.
          ${
            verdict.synthetic
              ? 'Synthetic benchmark — these passes are scaffolding, never claims. '
              : ''
          }Pre-calibration NISAR stream: re-validation on calibrated data is a mandatory
          gate.
        </div>
      </div>
      <div class="spacer"></div>
      <div class="verdict-run">
        ${
          loaded.reportLastModified
            ? `report written ${loaded.reportLastModified}`
            : 'run timestamp not recorded in the report'
        }<br />
        ${report.detector} ${report.detectorVersion} · labels ${report.labelsVersion} · methodology
        ${report.methodologyVersion}
      </div>
    </div>
  `
}

function statusClass(status: KillCriterionStatus): string {
  return status === 'PASS' ? 'pass' : status === 'FAIL' ? 'fail' : 'insufficient'
}

function statusLabel(status: KillCriterionStatus): string {
  return status === 'INSUFFICIENT_DATA' ? 'INSUFF. DATA' : status
}

function renderCriteria(report: BenchmarkReport): Raw {
  return html`
    <div class="rows">
      ${report.killCriteria.criteria.map(
        (criterion) => html`
          <div class="criterion">
            <div>
              <div class="criterion-name">${criterion.name}</div>
              ${criterion.note ? html`<div class="criterion-note">${criterion.note}</div>` : ''}
            </div>
            <div class="criterion-threshold">${criterion.threshold}</div>
            <div class="criterion-observed">${criterion.observed}</div>
            <div class="criterion-status ${statusClass(criterion.status)}">
              ${statusLabel(criterion.status)}
            </div>
          </div>
        `,
      )}
    </div>
  `
}

function renderMetrics(report: BenchmarkReport): Raw {
  const latency = report.medianDetectionLatencyDays
  const lead = report.medianLeadOverOpticalDays
  return html`
    <div class="metrics">
      ${metric(
        'Precision',
        fixed(report.eventPrecision, 2),
        null,
        `${report.truePositives} / ${report.nDetections} detections matched`,
      )}
      ${metric(
        'Recall',
        fixed(report.eventRecall, 2),
        null,
        `${report.truePositives} / ${report.nEvents} confirmed events`,
      )}
      ${metric('F1', fixed(report.f1, 2), null, 'event-level, 1:1 greedy')}
      ${metric(
        'Median latency',
        latency === null ? 'n/a' : String(latency),
        latency === null ? null : 'd',
        latency === null ? 'no matched events' : '12-d revisit is the floor',
      )}
      ${metric(
        'Lead vs optical',
        lead === null ? 'n/a' : lead > 0 ? `+${lead}` : String(lead),
        lead === null ? null : 'd',
        `n=${report.nEventsWithOpticalRecord} with optical dates`,
        lead !== null && lead > 0,
      )}
    </div>
  `
}

function metric(
  label: string,
  value: string,
  unit: string | null,
  sub: string,
  highlight = false,
): Raw {
  return html`
    <div class="card">
      <div class="metric-label">${label}</div>
      <div class="metric-value ${highlight ? 'is-lead' : ''}">
        ${value}${unit ? html`<span class="metric-unit"> ${unit}</span>` : ''}
      </div>
      <div class="metric-sub">${sub}</div>
    </div>
  `
}

function renderCalibration(report: BenchmarkReport): Raw {
  const { bins, expectedCalibrationError } = report.calibration
  if (bins.length === 0) {
    return html`
      <div class="card">
        <div class="card-note">No detections to bin — the harness emitted no calibration bins.</div>
      </div>
    `
  }
  return html`
    <div class="card">
      <div class="calib-grid">
        <div class="calib-head">SCORE BIN</div>
        <div class="calib-head">N</div>
        <div class="calib-head">CONFIRMED RATE</div>
        <div class="calib-head">EXPECT</div>
        ${bins.map(
          (bin) => html`
            <div>${bin.bin}</div>
            <div class="calib-n">${bin.n}</div>
            <div class="calib-bar">
              <div
                class="calib-fill ${rateClass(bin.confirmRate)}"
                style="width:${Math.round(bin.confirmRate * 100)}%"
              ></div>
            </div>
            <div class="calib-expect">${fixed(bin.meanScore, 2)}</div>
          `,
        )}
      </div>
      <div class="card-note">
        ${
          expectedCalibrationError === null
            ? 'Expected calibration error not reported.'
            : `Expected calibration error ${fixed(expectedCalibrationError, 3)}.`
        }
        ${worstBinNote(bins)}
      </div>
    </div>
  `
}

/** Names the worst-calibrated bin from the data rather than asserting one. */
function worstBinNote(bins: CalibrationBin[]): string {
  let worst: CalibrationBin | null = null
  let worstGap = 0
  for (const bin of bins) {
    const gap = Math.abs(bin.meanScore - bin.confirmRate)
    if (gap > worstGap) {
      worst = bin
      worstGap = gap
    }
  }
  if (!worst || worstGap < 0.05) return 'No bin is off its score by more than 0.05.'
  const direction = worst.confirmRate < worst.meanScore ? 'under-confirms' : 'over-confirms'
  return `The ${worst.bin} bin ${direction} (${percent(worst.confirmRate)} at mean score ${fixed(
    worst.meanScore,
    2,
  )}, n=${worst.n}) — overconfidence is a defect, not a rounding error.`
}

function rateClass(rate: number): string {
  return rate >= 0.7 ? '' : rate >= 0.5 ? 'mid' : 'low'
}

function renderRecallByArea(report: BenchmarkReport): Raw {
  const byBin = new Map(report.recallByAreaHa.map((entry) => [entry.bin, entry.recall]))
  return html`
    <div class="card">
      <div class="recall-bars">
        ${AREA_BINS_HA.map((bin) => {
          const recall = byBin.get(bin)
          return html`
            <div class="recall-col">
              <div class="recall-value ${recall === undefined ? 'is-empty' : ''}">
                ${recall === undefined ? 'n/a' : fixed(recall, 2)}
              </div>
              <div
                class="recall-bar ${recall === undefined ? 'empty' : rateClass(recall)}"
                style="height:${recall === undefined ? 4 : Math.max(4, Math.round(recall * 100))}${recall === undefined ? 'px' : '%'}"
              ></div>
            </div>
          `
        })}
      </div>
      <div class="recall-axis">
        ${AREA_BINS_HA.map(
          (bin) =>
            html`<span
              >${bin} ha<br />${byBin.has(bin) ? 'scored' : 'no labeled events'}</span
            >`,
        )}
      </div>
      <div class="card-note">
        The minimum-detectable-size curve. The harness omits bins with no labeled events rather
        than reporting them as zero, and emits no per-bin event count — so the bars show recall
        only.
      </div>
    </div>
  `
}

/**
 * There is no run index: `run_benchmark` overwrites one report per benchmark
 * and keeps no history. This table therefore shows the loaded run alone.
 */
function renderRuns(loaded: LoadedBenchmark): Raw {
  const { report } = loaded
  const verdictClass = !report.killCriteria.alive
    ? 'dead'
    : report.killCriteria.synthetic
      ? 'synthetic'
      : 'alive'
  const verdictText = !report.killCriteria.alive
    ? 'kill condition met'
    : report.killCriteria.synthetic
      ? 'scaffolding ⚠ synthetic'
      : 'alive'
  return html`
    <div class="rows runs">
      <div class="run-row is-head">
        <div>REPORT WRITTEN</div>
        <div>BENCHMARK</div>
        <div>DETECTOR · LABELS</div>
        <div>PRECISION</div>
        <div>RECALL</div>
        <div>VERDICT</div>
      </div>
      <div class="run-row">
        <div>${loaded.reportLastModified ?? 'not recorded'}</div>
        <div>${report.benchmark}</div>
        <div class="run-detector">
          ${report.detector} ${report.detectorVersion} · labels ${report.labelsVersion}
        </div>
        <div>${fixed(report.eventPrecision, 2)}</div>
        <div>${fixed(report.eventRecall, 2)}</div>
        <div class="run-verdict ${verdictClass}">${verdictText}</div>
      </div>
    </div>
    <div class="note">
      Only the currently loaded run is shown: the pipeline keeps no run index — each benchmark has
      exactly one report path, overwritten in place. Load another run with
      <code>?report=</code>.
    </div>
  `
}
