import { describe, expect, test } from 'bun:test'
import type { Geometry } from 'geojson'

import {
  applyFilter,
  buildRows,
  centroid,
  daysBetween,
  detectionWindow,
  distanceM,
  filterCounts,
  matchDetections,
  queueFor,
  sortQueue,
  statusFromMatch,
  temporallyCompatible,
} from './triage'
import type { Detection, DisturbanceEvent, MatchingTolerances } from './types'

const TOLERANCES: MatchingTolerances = {
  maxCentroidDistanceM: 500,
  minSpatialIou: 0,
  temporalWindowDays: 36,
}

function square(lon: number, lat: number, halfDeg = 0.002): Detection['geometry'] {
  return {
    type: 'Polygon',
    coordinates: [
      [
        [lon - halfDeg, lat - halfDeg],
        [lon + halfDeg, lat - halfDeg],
        [lon + halfDeg, lat + halfDeg],
        [lon - halfDeg, lat + halfDeg],
        [lon - halfDeg, lat - halfDeg],
      ],
    ],
  }
}

function detection(over: Partial<Detection> & Pick<Detection, 'id'>): Detection {
  return {
    geometry: square(-55, -7),
    firstSeen: '2026-02-13T00:00:00',
    lastSeen: '2026-03-01T00:00:00',
    score: 0.5,
    persistencePasses: 2,
    areaHa: 4,
    ...over,
  }
}

function label(over: Partial<DisturbanceEvent> & Pick<DisturbanceEvent, 'id'>): DisturbanceEvent {
  return {
    geometry: square(-55, -7),
    dateWindow: { start: '2026-02-01', end: '2026-02-13' },
    eventClass: 'access-road',
    status: 'confirmed',
    biome: 'toy',
    evidenceSource: 'synthetic fixture — generated, not observed',
    locationPrecision: 'exact',
    ...over,
  }
}

/**
 * Regression fixture. Every `centroid` below was produced by shapely 2.1.2 —
 * `shapely.geometry.shape(geometry).centroid` — which is the exact call
 * understory_detect.scoring.match_detections makes. They were generated by a
 * throwaway script against this list, never computed by hand and never taken
 * from the code under test: if the two sides disagree the Alerts tab and the
 * Report tab disagree about what matched.
 *
 * The list covers what the label JSON Schema permits and the Python side
 * accepts: interior rings, concave shells, either winding, multi-part
 * geometries with very different-sized parts, lines with uneven segments,
 * geometry collections, and the degenerate cases where GEOS drops a dimension
 * (a zero-area polygon answers with its boundary, a zero-length line with its
 * vertex).
 */
const SHAPELY_CENTROIDS: { name: string; geometry: Geometry; centroid: [number, number] }[] = [
  {
    name: 'square',
    geometry: {
      type: 'Polygon',
      coordinates: [
        [
          [0, 0],
          [1, 0],
          [1, 1],
          [0, 1],
          [0, 0],
        ],
      ],
    },
    centroid: [0.5, 0.5],
  },
  {
    name: 'square-cw',
    geometry: {
      type: 'Polygon',
      coordinates: [
        [
          [0, 0],
          [0, 1],
          [1, 1],
          [1, 0],
          [0, 0],
        ],
      ],
    },
    centroid: [0.5, 0.5],
  },
  {
    name: 'concave-l',
    geometry: {
      type: 'Polygon',
      coordinates: [
        [
          [0, 0],
          [4, 0],
          [4, 1],
          [1, 1],
          [1, 3],
          [0, 3],
          [0, 0],
        ],
      ],
    },
    centroid: [1.5, 1.0],
  },
  {
    name: 'polygon-with-hole',
    geometry: {
      type: 'Polygon',
      coordinates: [
        [
          [0, 0],
          [10, 0],
          [10, 10],
          [0, 10],
          [0, 0],
        ],
        [
          [1, 1],
          [4, 1],
          [4, 4],
          [1, 4],
          [1, 1],
        ],
      ],
    },
    centroid: [5.247252747252747, 5.247252747252747],
  },
  {
    name: 'polygon-hole-same-winding',
    geometry: {
      type: 'Polygon',
      coordinates: [
        [
          [0, 0],
          [10, 0],
          [10, 10],
          [0, 10],
          [0, 0],
        ],
        [
          [1, 1],
          [1, 4],
          [4, 4],
          [4, 1],
          [1, 1],
        ],
      ],
    },
    centroid: [5.247252747252747, 5.247252747252747],
  },
  {
    name: 'multipolygon-uneven',
    geometry: {
      type: 'MultiPolygon',
      coordinates: [
        [
          [
            [0, 0],
            [10, 0],
            [10, 10],
            [0, 10],
            [0, 0],
          ],
        ],
        [
          [
            [100, 100],
            [100.5, 100],
            [100.5, 100.5],
            [100, 100.5],
            [100, 100],
          ],
        ],
      ],
    },
    centroid: [5.237531172069826, 5.237531172069826],
  },
  {
    name: 'multipolygon-with-hole',
    geometry: {
      type: 'MultiPolygon',
      coordinates: [
        [
          [
            [0, 0],
            [10, 0],
            [10, 10],
            [0, 10],
            [0, 0],
          ],
          [
            [1, 1],
            [4, 1],
            [4, 4],
            [1, 4],
            [1, 1],
          ],
        ],
        [
          [
            [20, 20],
            [22, 20],
            [22, 22],
            [20, 22],
            [20, 20],
          ],
        ],
      ],
    },
    centroid: [5.910526315789474, 5.910526315789474],
  },
  {
    name: 'linestring-uneven',
    geometry: {
      type: 'LineString',
      coordinates: [
        [0, 0],
        [10, 0],
        [11, 0],
        [11, 5],
      ],
    },
    centroid: [7.21875, 0.78125],
  },
  {
    name: 'linestring-diagonal',
    geometry: {
      type: 'LineString',
      coordinates: [
        [-55.01, -7.01],
        [-54.99, -6.99],
        [-54.985, -6.989],
      ],
    },
    centroid: [-54.99809072915021, -6.998396212486182],
  },
  {
    name: 'linestring-repeated-vertex',
    geometry: {
      type: 'LineString',
      coordinates: [
        [0, 0],
        [0, 0],
        [4, 0],
        [4, 1],
      ],
    },
    centroid: [2.4, 0.1],
  },
  {
    name: 'linestring-zero-length',
    geometry: {
      type: 'LineString',
      coordinates: [
        [-55, -7],
        [-55, -7],
      ],
    },
    centroid: [-55.0, -7.0],
  },
  {
    name: 'multilinestring-uneven',
    geometry: {
      type: 'MultiLineString',
      coordinates: [
        [
          [0, 0],
          [10, 0],
        ],
        [
          [0, 5],
          [0, 6],
        ],
      ],
    },
    centroid: [4.545454545454546, 0.5],
  },
  {
    name: 'multilinestring-one-degenerate',
    geometry: {
      type: 'MultiLineString',
      coordinates: [
        [
          [0, 0],
          [10, 0],
        ],
        [
          [50, 50],
          [50, 50],
        ],
      ],
    },
    centroid: [5.0, 0.0],
  },
  {
    name: 'polygon-collinear',
    geometry: {
      type: 'Polygon',
      coordinates: [
        [
          [0, 0],
          [10, 0],
          [1, 0],
          [0, 0],
        ],
      ],
    },
    centroid: [5.0, 0.0],
  },
  {
    name: 'polygon-collinear-reversed',
    geometry: {
      type: 'Polygon',
      coordinates: [
        [
          [0, 0],
          [1, 0],
          [10, 0],
          [0, 0],
        ],
      ],
    },
    centroid: [5.0, 0.0],
  },
  {
    name: 'polygon-single-point',
    geometry: {
      type: 'Polygon',
      coordinates: [
        [
          [-55, -7],
          [-55, -7],
          [-55, -7],
        ],
      ],
    },
    centroid: [-55.0, -7.0],
  },
  {
    name: 'point',
    geometry: { type: 'Point', coordinates: [-54.9, -6.9] },
    centroid: [-54.9, -6.9],
  },
  {
    name: 'multipoint',
    geometry: {
      type: 'MultiPoint',
      coordinates: [
        [0, 0],
        [0, 0],
        [3, 6],
      ],
    },
    centroid: [1.0, 2.0],
  },
  {
    name: 'collection-area-wins',
    geometry: {
      type: 'GeometryCollection',
      geometries: [
        {
          type: 'Polygon',
          coordinates: [
            [
              [0, 0],
              [2, 0],
              [2, 2],
              [0, 2],
              [0, 0],
            ],
          ],
        },
        {
          type: 'LineString',
          coordinates: [
            [100, 100],
            [200, 200],
          ],
        },
        { type: 'Point', coordinates: [-40, -40] },
      ],
    },
    centroid: [1.0, 1.0],
  },
  {
    name: 'collection-line-wins',
    geometry: {
      type: 'GeometryCollection',
      geometries: [
        {
          type: 'LineString',
          coordinates: [
            [0, 0],
            [10, 0],
          ],
        },
        { type: 'Point', coordinates: [-40, -40] },
      ],
    },
    centroid: [5.0, 0.0],
  },
  {
    name: 'collection-points-only',
    geometry: {
      type: 'GeometryCollection',
      geometries: [
        { type: 'Point', coordinates: [0, 0] },
        { type: 'Point', coordinates: [4, 8] },
      ],
    },
    centroid: [2.0, 4.0],
  },
  {
    name: 'collection-flat-polygon-and-line',
    geometry: {
      type: 'GeometryCollection',
      geometries: [
        {
          type: 'Polygon',
          coordinates: [
            [
              [0, 0],
              [10, 0],
              [1, 0],
              [0, 0],
            ],
          ],
        },
        {
          type: 'LineString',
          coordinates: [
            [0, 5],
            [0, 9],
          ],
        },
      ],
    },
    centroid: [4.166666666666667, 1.1666666666666667],
  },
  {
    name: 'multipolygon-one-collapsed',
    geometry: {
      type: 'MultiPolygon',
      coordinates: [
        [
          [
            [0, 0],
            [10, 0],
            [10, 10],
            [0, 10],
            [0, 0],
          ],
        ],
        [
          [
            [50, 50],
            [60, 50],
            [51, 50],
            [50, 50],
          ],
        ],
      ],
    },
    centroid: [5.0, 5.0],
  },
  {
    name: 'toy-road-corridor',
    geometry: {
      type: 'Polygon',
      coordinates: [
        [
          [-55.01, -6.995],
          [-54.99, -6.995],
          [-54.99, -7.005],
          [-55.01, -7.005],
          [-55.01, -6.995],
        ],
      ],
    },
    centroid: [-55.0, -6.999999999999999],
  },
  {
    name: 'polygon-bowtie',
    geometry: {
      type: 'Polygon',
      coordinates: [
        [
          [0, 0],
          [2, 0],
          [0, 2],
          [2, 2],
          [0, 0],
        ],
      ],
    },
    centroid: [1.0, 1.0],
  },
  {
    name: 'collection-bowtie-and-square',
    geometry: {
      type: 'GeometryCollection',
      geometries: [
        {
          type: 'Polygon',
          coordinates: [
            [
              [0, 0],
              [2, 0],
              [0, 2],
              [2, 2],
              [0, 0],
            ],
          ],
        },
        {
          type: 'Polygon',
          coordinates: [
            [
              [10, 10],
              [12, 10],
              [12, 12],
              [10, 12],
              [10, 10],
            ],
          ],
        },
      ],
    },
    centroid: [11.0, 11.333333333333334],
  },
]

describe('centroid', () => {
  test('reproduces shapely for every geometry the label schema allows', () => {
    for (const fixture of SHAPELY_CENTROIDS) {
      const [lon, lat] = centroid(fixture.geometry)
      const delta = Math.max(
        Math.abs(lon - fixture.centroid[0]),
        Math.abs(lat - fixture.centroid[1]),
      )
      // Reported as an object so a failure names the geometry that drifted.
      expect({ case: fixture.name, matchesShapely: delta <= 1e-9 }).toEqual({
        case: fixture.name,
        matchesShapely: true,
      })
    }
  })

  test('area-weighted centroid of a square is its middle', () => {
    const [lon, lat] = centroid(square(-55.01, -7.02))
    expect(lon).toBeCloseTo(-55.01, 6)
    expect(lat).toBeCloseTo(-7.02, 6)
  })

  test('point geometry is its own centroid', () => {
    expect(centroid({ type: 'Point', coordinates: [-54.9, -6.9] })).toEqual([-54.9, -6.9])
  })

  test('a hole pulls the centroid away from the hole, not to the vertex mean', () => {
    // Vertex mean of shell + hole would be (2.5, 2.5); shapely says 5.2472….
    const [lon, lat] = centroid({
      type: 'Polygon',
      coordinates: [
        [
          [0, 0],
          [10, 0],
          [10, 10],
          [0, 10],
          [0, 0],
        ],
        [
          [1, 1],
          [4, 1],
          [4, 4],
          [1, 4],
          [1, 1],
        ],
      ],
    })
    expect(lon).toBeCloseTo(5.247252747252747, 12)
    expect(lat).toBeCloseTo(5.247252747252747, 12)
  })

  test('a line is length-weighted, not vertex-averaged', () => {
    // A schema-valid access-road label: one long segment, two short ones. The
    // vertex mean would be (8, 1.25); shapely walks the length.
    const [lon, lat] = centroid({
      type: 'LineString',
      coordinates: [
        [0, 0],
        [10, 0],
        [11, 0],
        [11, 5],
      ],
    })
    expect(lon).toBeCloseTo(7.21875, 12)
    expect(lat).toBeCloseTo(0.78125, 12)
  })

  test('a collapsed polygon answers with its boundary, like GEOS', () => {
    const [lon, lat] = centroid({
      type: 'Polygon',
      coordinates: [
        [
          [0, 0],
          [10, 0],
          [1, 0],
          [0, 0],
        ],
      ],
    })
    expect(lon).toBeCloseTo(5, 12)
    expect(lat).toBeCloseTo(0, 12)
  })

  test('degenerate ring falls back to the vertex mean', () => {
    const [lon, lat] = centroid({
      type: 'Polygon',
      coordinates: [
        [
          [-55, -7],
          [-55, -7],
          [-55, -7],
        ],
      ],
    })
    expect(lon).toBeCloseTo(-55, 9)
    expect(lat).toBeCloseTo(-7, 9)
  })

  test('an empty geometry has no centroid and so matches nothing', () => {
    // Shapely answers POINT EMPTY and the Python matcher raises reading .x off
    // it. NaN makes every distance comparison false — no match at 0°,0°.
    const [lon, lat] = centroid({ type: 'Polygon', coordinates: [] })
    expect(Number.isNaN(lon)).toBe(true)
    expect(Number.isNaN(lat)).toBe(true)
    expect(distanceM([lon, lat], [-55, -7]) <= 500).toBe(false)
  })
})

describe('distanceM', () => {
  test('matches the scoring harness approximation', () => {
    // 0.001 degrees of latitude = 110.54 m in scoring._distance_m.
    expect(distanceM([-55, -7], [-55, -7.001])).toBeCloseTo(110.54, 2)
  })
})

describe('temporal compatibility', () => {
  const event = label({ id: 'l1' })

  test('inside the padded window', () => {
    expect(temporallyCompatible(detection({ id: 'd', firstSeen: '2026-03-01' }), event, 36)).toBe(
      true,
    )
  })

  test('outside the padded window', () => {
    expect(temporallyCompatible(detection({ id: 'd', firstSeen: '2026-05-01' }), event, 36)).toBe(
      false,
    )
  })
})

describe('matchDetections', () => {
  test('greedy one-to-one, highest score first', () => {
    const near = detection({ id: 'near', score: 0.9, geometry: square(-55.0005, -7) })
    const far = detection({ id: 'far', score: 0.8, geometry: square(-55.001, -7) })
    const matches = matchDetections([far, near], [label({ id: 'l1' })], TOLERANCES)
    expect(matches.get('near')?.label.id).toBe('l1')
    expect(matches.has('far')).toBe(false)
  })

  test('nothing matches beyond the distance tolerance', () => {
    const matches = matchDetections(
      [detection({ id: 'd', geometry: square(-55.02, -7) })],
      [label({ id: 'l1' })],
      TOLERANCES,
    )
    expect(matches.size).toBe(0)
  })

  test('confirmed labels are matched before rejected ones', () => {
    // Both labels sit within tolerance; the confirmed pass runs first, so the
    // single detection lands on the confirmed label exactly as the harness does.
    const matches = matchDetections(
      [detection({ id: 'd', geometry: square(-55.001, -7) })],
      [
        label({ id: 'rejected-label', status: 'rejected', geometry: square(-55.0005, -7) }),
        label({ id: 'confirmed-label', status: 'confirmed', geometry: square(-55.001, -7) }),
      ],
      TOLERANCES,
    )
    expect(matches.get('d')?.label.id).toBe('confirmed-label')
  })

  test('a leftover detection can still land on a verified false alarm', () => {
    const matches = matchDetections(
      [
        detection({ id: 'strong', score: 0.9, geometry: square(-55, -7) }),
        detection({ id: 'weak', score: 0.4, geometry: square(-55.001, -7) }),
      ],
      [
        label({ id: 'confirmed-label', geometry: square(-55, -7) }),
        label({ id: 'rain', status: 'rejected', geometry: square(-55.001, -7) }),
      ],
      TOLERANCES,
    )
    expect(matches.get('strong')?.label.id).toBe('confirmed-label')
    expect(matches.get('weak')?.label.id).toBe('rain')
  })

  test('reports centroid separation, latency and optical lead', () => {
    const matches = matchDetections(
      [detection({ id: 'd', firstSeen: '2026-02-23T00:00:00', geometry: square(-55, -7.001) })],
      [label({ id: 'l1', opticalAlertDate: '2026-03-20' })],
      TOLERANCES,
    )
    const match = matches.get('d')
    expect(match?.distanceM).toBeCloseTo(110.54, 2)
    expect(match?.latencyDays).toBe(22)
    expect(match?.leadOverOpticalDays).toBe(25)
  })

  test('no optical alert date means no lead, not a zero', () => {
    const matches = matchDetections([detection({ id: 'd' })], [label({ id: 'l1' })], TOLERANCES)
    expect(matches.get('d')?.leadOverOpticalDays).toBeNull()
  })
})

describe('status resolution', () => {
  test('a detection inherits the status of the label it matched', () => {
    const rows = buildRows(
      [
        detection({ id: 'hit', score: 0.9, geometry: square(-55, -7) }),
        detection({ id: 'alarm', score: 0.6, geometry: square(-55.02, -7) }),
        detection({ id: 'orphan', score: 0.3, geometry: square(-55.5, -7) }),
      ],
      [
        label({ id: 'confirmed-label', geometry: square(-55, -7) }),
        label({ id: 'rain', status: 'rejected', geometry: square(-55.02, -7) }),
      ],
      TOLERANCES,
    )
    expect(rows.map((row) => row.status)).toEqual(['confirmed', 'rejected', 'candidate'])
    expect(rows.every((row) => !row.overridden)).toBe(true)
  })

  test('a local triage decision wins over the label-derived status', () => {
    const rows = buildRows(
      [detection({ id: 'hit', geometry: square(-55, -7) })],
      [label({ id: 'confirmed-label' })],
      TOLERANCES,
      { hit: 'rejected' },
    )
    expect(rows[0]?.status).toBe('rejected')
    expect(rows[0]?.overridden).toBe(true)
  })

  test('an unmatched detection is a candidate, never a confirmation', () => {
    expect(statusFromMatch(null)).toBe('candidate')
  })

  test('a candidate label does not confirm a detection', () => {
    const rows = buildRows(
      [detection({ id: 'd' })],
      [label({ id: 'unreviewed', status: 'candidate' })],
      TOLERANCES,
    )
    expect(rows[0]?.status).toBe('candidate')
    expect(rows[0]?.match?.label.id).toBe('unreviewed')
  })
})

describe('queue', () => {
  const rows = buildRows(
    [
      detection({
        id: 'a',
        score: 0.9,
        firstSeen: '2026-01-10T00:00:00',
        geometry: square(-55, -7),
      }),
      detection({
        id: 'b',
        score: 0.4,
        firstSeen: '2026-03-02T00:00:00',
        geometry: square(-56, -8),
      }),
      detection({
        id: 'c',
        score: 0.7,
        firstSeen: '2026-02-14T00:00:00',
        geometry: square(-57, -9),
      }),
    ],
    [label({ id: 'confirmed-label', geometry: square(-55, -7) })],
    TOLERANCES,
  )

  test('counts every filter bucket', () => {
    expect(filterCounts(rows)).toEqual({ all: 3, candidate: 2, confirmed: 1, rejected: 0 })
  })

  test('filters by resolved status', () => {
    expect(applyFilter(rows, 'confirmed').map((row) => row.detection.id)).toEqual(['a'])
    expect(applyFilter(rows, 'all')).toHaveLength(3)
  })

  test('sorts by score, highest first', () => {
    expect(sortQueue(rows, 'score').map((row) => row.detection.id)).toEqual(['a', 'c', 'b'])
  })

  test('sorts by recency, newest first', () => {
    expect(sortQueue(rows, 'recent').map((row) => row.detection.id)).toEqual(['b', 'c', 'a'])
  })

  test('queueFor filters then sorts', () => {
    expect(queueFor(rows, 'candidate', 'score').map((row) => row.detection.id)).toEqual(['c', 'b'])
  })
})

describe('windows and dates', () => {
  test('detection window spans earliest first_seen to latest last_seen', () => {
    expect(
      detectionWindow([
        detection({ id: 'a', firstSeen: '2026-02-13T00:00:00', lastSeen: '2026-03-01T00:00:00' }),
        detection({ id: 'b', firstSeen: '2026-01-08T00:00:00', lastSeen: '2026-02-01T00:00:00' }),
      ]),
    ).toEqual({ start: '2026-01-08', end: '2026-03-01' })
  })

  test('no detections means no window rather than a made-up one', () => {
    expect(detectionWindow([])).toBeNull()
  })

  test('day arithmetic ignores the time part, like the Python side', () => {
    expect(daysBetween('2026-02-01', '2026-02-23T12:00:00')).toBe(22)
  })
})
